---
- id: frigate
  name: Guided Missile Frigate
  allegiance: hostile
  components:
    - kind: movement
      data:
        max_speed_knots: 30.0
        acceleration: 2.0
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: hostile_faker
          symbol_set: surface
          status: present_fully_capable
          hqtfd: not_applicable
          amplifier: unspecified
          entity: code_120204
          modifier_one: code_00
          modifier_two: code_00
