- id: gps-20185
  name: NAVSTAR 15 (USA 42)
  allegiance: friendly
  components:
    - kind: space_orbit
      data:
        line1: "1 20185U 89064A   26082.20102767  .00000026  00000+0  00000+0 0  9992"
        line2: "2 20185  54.9066  92.3020 0012371 319.2363 217.1486  1.86088387254600"
        fov_half_angle_deg: 5.0
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: friend
          symbol_set: space
          status: present
          hqtfd: not_applicable
          amplifier: unspecified
          entity: code_110700
          modifier_one: code_02
          modifier_two: code_00
