- id: gps-22231
  name: NAVSTAR 28 (USA 85)
  allegiance: friendly
  components:
    - kind: space_orbit
      data:
        line1: "1 22231U 92079A   26087.12172688  .00000048  00000+0  00000+0 0  9995"
        line2: "2 22231  55.5225 116.6134 0024499   1.1164 358.9551  1.89108479 60604"
        fov_half_angle_deg: 5.0
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: friend
          symbol_set: space
          status: present
          hqtfd: not_applicable
          amplifier: unspecified
          entity: code_110700
          modifier_one: code_02
          modifier_two: code_00
