- id: gps-25030
  name: NAVSTAR 44 (USA 135)
  allegiance: friendly
  components:
    - kind: space_orbit
      data:
        line1: "1 25030U 97067A   26086.41991772 -.00000034  00000+0  00000+0 0  9997"
        line2: "2 25030  55.5948 176.2769 0020414 259.4619 170.8624  1.88437659205155"
        fov_half_angle_deg: 5.0
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: friend
          symbol_set: space
          status: present
          hqtfd: not_applicable
          amplifier: unspecified
          entity: code_110700
          modifier_one: code_02
          modifier_two: code_00
