- id: gps-19802
  name: NAVSTAR 13 (USA 35)
  allegiance: friendly
  components:
    - kind: space_orbit
      data:
        line1: "1 19802U 89013A   26086.25457213  .00000042  00000+0  00000+0 0  9996"
        line2: "2 19802  54.9733  97.3893 0044030 248.8108 199.3104  1.85325525256752"
        fov_half_angle_deg: 5.0
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: friend
          symbol_set: space
          status: present
          hqtfd: not_applicable
          amplifier: unspecified
          entity: code_110700
          modifier_one: code_02
          modifier_two: code_00
