- id: pentagon
  name: The Pentagon
  allegiance: friendly
  components:
    - kind: symbol
      data:
        sidc_template:
          version: "10"
          context: reality
          standard_identity: friend
          symbol_set: installation
          status: present
          hqtfd: not_applicable
          amplifier: unspecified
          # 110000: Military Installation
          entity: code_110000
          modifier_one: code_00
          modifier_two: code_00
        # When true, Cesium loads the GLB instead of milsymbol (file: client/public/…). Default false.
        map_icon_glb_override: false
        map_icon_glb_url: models/low_poly_pentagon.glb
